ARG DOCKERSRC=frommakefile
#
FROM ${DOCKERSRC}
#
# ARG PUID=1000
# ARG PGID=1000
#
RUN set -xe \
    && apk add --no-cache --purge -uU tzdata dhcp \
    && touch /var/lib/dhcp/dhcpd.leases \
    && rm -rf /var/cache/apk/* /tmp/*
#
COPY root/ /
#
VOLUME /etc/dhcp/
#
EXPOSE 67/udp 67/tcp
#
ENTRYPOINT ["/init"]
